/******CHANGE FILE LOCATION******/

USE [master]
GO

/****** Object:  Database [UsersManagement]    Script Date: 06.1.2024 21:57:36 ******/
CREATE DATABASE [UsersManagement]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersManagement', FILENAME = N'D:\DATA\UsersManagement.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UsersManagement_log', FILENAME = N'D:\DATA\UsersManagement_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersManagement].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsersManagement] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersManagement] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersManagement] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersManagement] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersManagement] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersManagement] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersManagement] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersManagement] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersManagement] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersManagement] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersManagement] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersManagement] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersManagement] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersManagement] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersManagement] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsersManagement] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersManagement] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersManagement] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersManagement] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersManagement] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersManagement] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersManagement] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsersManagement] SET RECOVERY FULL 
GO

ALTER DATABASE [UsersManagement] SET  MULTI_USER 
GO

ALTER DATABASE [UsersManagement] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersManagement] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsersManagement] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsersManagement] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UsersManagement] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UsersManagement] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UsersManagement] SET  READ_WRITE 
GO


